---
title: "forest summary"
author: "Kate Miller"
date: "2/2/2021"
output: html_document
params: 
  park_code: ROVA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r depends, echo = FALSE, results = 'hide', message = FALSE}
windowsFonts(A = windowsFont("Arial"))
park_code = "ROVA"
#park_code <- params$park_code

library(tidyverse)
library(forestNETN)
library(grid) # for parks with multiple units
library(gtable) # for extracting the legend from ggplot objects

importData()

pie_int = 40 # ~Size of smallest pie in m. Used in 02_calculate_metric_functions to calc. fig_radius
  # pie_int + pie_slope*0.01 will be the smallest pie size mapped
pie_slope = 200 # Expansion factor to increase pie size by (pie_int + pie_slope(std_var)). 
  # Used in 02_calculate_metric_functions to calc. fig_radius

# Note: 00 scripts will eventually be added to a package
source("00_helper_functions.R") # nudge_XY and dependency functions
source("00_helper_plotting_functions.R") # pie, chart and corresponding legend functions
source("01_compile_base_layers.R") # load spatial data and set up metric-level templates/legends
source("02_calculate_metric_functions.R") # metric summary functions
source(paste0("03_park_template_", park_code, ".R")) # Creates park-specific base maps and scales_tbl

```

```{r, regsize_nudge}
# Calc. regen by size class per plot
regen_by_sizeclass(park_code, 2016, 2019, pie_int, pie_slope) # adds regsize_df & regsize_long to GE
# Nudge XY coords if pies will overlap
regsize_nudge <- nudge_XY(regsize_df, x = "X", y = "Y", stdvar = "totreg_std2", 
                          max_iter = 20, min_shift = 0.5, quiet = FALSE) 

#table(complete.cases(regsize_nudge$X_text))

```

```{r, regsize_pies}
# Create list of pies
vama_list <- sort(unique(regsize_nudge$Plot_Name[regsize_nudge$Unit == "VAMA"]))
rova_list <- sort(unique(regsize_nudge$Plot_Name[regsize_nudge$Unit != "VAMA"]))

vama_regsize_pies <- map(vama_list, 
                         ~pie_regsize_fun(regsize_long %>% filter(Unit == "VAMA"), .x,
                                          y_var = dens, grp_var = size_class, std_var = "totreg_std2"))
rova_regsize_pies <- map(rova_list, 
                         ~pie_regsize_fun(regsize_long %>% filter(Unit != "VAMA"), .x,
                                          y_var = dens, grp_var = size_class, std_var = "totreg_std2"))

```

```{r, regsize_map}
rova_sf <- st_as_sf(regsize_nudge %>% filter(Unit != "VAMA"), 
                    coords = c("X_nudge", "Y_nudge"), crs = 5070) 
vama_sf <- st_as_sf(regsize_nudge %>% filter(Unit == "VAMA"), 
                    coords = c("X_nudge", "Y_nudge"), crs = 5070)

rova_text <- st_as_sf(regsize_nudge %>% filter(Unit != "VAMA"), 
                      coords = c("X_text", "Y_text"), crs = 5070)
vama_text <- st_as_sf(regsize_nudge %>% filter(Unit == "VAMA"),
                      coords = c("X_text", "Y_text"), crs = 5070)

rova_buff <- st_buffer(rova_sf, dist = rova_sf$fig_radius)
vama_buff <- st_buffer(vama_sf, dist = vama_sf$fig_radius)

rova_reg <- rova +  
  tm_shape(rova_sf %>% arrange(-fig_radius))+
  tm_symbols(size = "fig_area",
             scale = 2.5,
             size.max = max(regsize_nudge$fig_area),
             #size.lim = c(min(regsize_nudge$fig_area), max(regsize_nudge$fig_area)), 
             perceptual = TRUE,
             shape = "Plot_Name", 
             group = "Charts", # pie charts
             shapes = rova_regsize_pies,
             border.col = NA, 
             border.lwd = NA)+
  {if(nrow(rova_sf %>% filter(totreg_std2 == 0))>0) # add symbols if no regen
    tm_shape(rova_sf %>% filter(totreg_std2 == 0))+
    tm_dots(shape = 24, border.col = "white", border.lwd = 1.8, size = 0.4)+
    tm_shape(rova_sf %>% filter(totreg_std2 == 0))+
    tm_dots(shape = 24, col = "#ff7f00", size = 0.3)}+
  
  tm_shape(rova_text)+ # add plot labels
  tm_text("plot_num", size = 0.6, #xmod = 0.01, ymod = -0.01,
          col = "black", bg.alpha = 0.8,
          just = 'center', shadow = "TRUE",
          fontface = 'bold')+
  # tm_shape(rova_buff)+
  # tm_borders(col = 'red')
  NULL

vama_reg <- vama +  
  tm_shape(vama_sf %>% arrange(-fig_radius))+
  tm_symbols(size = "fig_area",
             scale = 2.5, #2.5,
             size.max = max(regsize_nudge$fig_area),
             #size.lim = c(min(regsize_nudge$fig_area), max(regsize_nudge$fig_area)), #diam
             perceptual = TRUE,
             shape = "Plot_Name", 
             group = "Charts", # pie charts
             shapes = vama_regsize_pies,
             border.col = NA, 
             border.lwd = NA)+
  {if(nrow(vama_sf %>% filter(totreg_std2 == 0))>0)
    tm_shape(vama_sf %>% filter(totreg_std2 == 0))+ # add symbols if no regen
    tm_dots(shape = 24, border.col = "white", border.lwd = 1.8, size = 0.4)+
    tm_shape(vama_sf %>% filter(totreg_std2 == 0))+
    tm_dots(shape = 24, col = "#ff7f00", size = 0.3)}+
  tm_shape(vama_text)+
  tm_text("plot_num", size = 0.6, 
          col = "black", bg.alpha = 0.8,
          just = 'center', shadow = "TRUE",
          fontface = 'bold')+
  # tm_shape(vama_buff)+
  # tm_borders(col = 'red')
  NULL

# regsize_leg #ggplot with the pie legend
regsize_gleg <- gtable_filter(ggplot_gtable(ggplot_build(regsize_leg)), "guide-box")

# veg_leg #ggplot with habitat type legend (from script 03)
veg_gleg <- gtable_filter(ggplot_gtable(ggplot_build(veg_leg)), "guide-box")

# park boundary legend
bound_gleg <- gtable_filter(ggplot_gtable(ggplot_build(bound_leg)), "guide-box")

#leg1 = rbind(regsize_gleg, bound_gleg)

map_layout <- grid.layout(nrow = 5, ncol = 5, # 2 rows/col for margins
                          just = c("left"),
                          heights = unit(c(1, row1_height, 0.1, row2_height, 1), # adding 1 line margins
                                         c("lines", "null", "lines", "null", "lines")),
                          widths = unit(c(1, 0.6, col1_width, col2_width, 1),
                                        c("lines", "lines", "null", "null", "lines")))

#grid.show.layout(map_layout)
map_vp <- viewport(name = "map_vp", layout = map_layout)
#grid.locator()
# Save map
jpeg("ROVA_plot_text_nudge_1p.jpg", height = 8.5, width = 9.9, units = "in", res = 600)

grid.newpage()
grid.rect(gp = gpar(col = 'black', fill = "white"))
#maps
pushViewport(map_vp)
print(vama_reg, vp = viewport(layout.pos.row = 2, layout.pos.col = 2:3))
pushViewport(map_vp)
print(rova_reg, vp = viewport(layout.pos.row = 4, layout.pos.col = 3:4))
#popViewport(1)

#legends
pushViewport(viewport(x = 0.38, y = 0.68))
grid.draw(regsize_gleg)
popViewport()
pushViewport(viewport(x = 0.35, y = 0.547))
grid.draw(bound_gleg)
popViewport()
pushViewport(viewport(x = 0.77, y = 0.68))
grid.draw(veg_gleg)
dev.off()

```


